stages:
  - publishToNexus
  - deployToOpenShift

variables:
  OPENSHIFT_SERVER: https://openshift.ext.cetic.be:8443
  OPENSHIFT_DOMAIN: openshift.ext.cetic.be
  # Configure this variable in Secure Variables:
  # OPENSHIFT_TOKEN: my.openshift.token  
  NEXUS_SERVER: http://nexus.ext.cetic.be:8083
  NEXUS_USER: nexus-gitlab-ci
  # Configure Nexus password in Secure Variables:
  # NEXUS_PASSWORD: my.nexus.password  

.publish: &publish
  before_script:
    # openjdk-8-jdk, sbt and docker have been installed on the shared shell runner.
    # Nexus server URL has been added to the /etc/docker/daemon.json as "insecure-registries".
    # check version of Docker
    - docker --version
  script:
    # login to Nexus Docker repository
    - docker login -u "$NEXUS_USER" -p "$NEXUS_PASSWORD" "$NEXUS_SERVER"
    # build tsimulus-cluster
    - sbt clean package
    # publish Backend Docker image to Nexus
    - sbt "backend/docker:publish"
    # publish Frontend Docker image to Nexus
    #- sbt "frontend/docker:publish"
  
.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc project "tsaas"
  script:
    - echo deploy to OpenShift
    # remove old pods
    - "oc get services $APP 2> /dev/null && oc delete -f k8s/tsaas-backend-statefulset.yml"
    ## Issue when trying to delete the statefulset https://github.com/kubernetes/kubernetes/issues/59867 Bug car pas même version de kubectl client - seveur
    #- "oc delete -f k8s/tsimulus-frontend-deployment.yml"
    #- "oc delete -f k8s/tsimulus-backend-deployment.yml"
    # create new pods
    - "oc create -f k8s/tsaas-backend-statefulset.yml"
    #- "oc create -f k8s/tsimulus-frontend-deployment.yml"
    #- "oc create -f k8s/tsimulus-backend-deployment.yml"
    - "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"
    #- "oc get services $APP 2> /dev/null || oc new-app . --name=$APP"
    #- "oc start-build $APP --from-dir=. --follow || sleep 3s"
    #- "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"
    
deploy:
  <<: *deploy
  image: ebits/openshift-client:v3.6.0
  stage: deployToOpenShift
  tags:
    - docker
  variables:
    APP: tsaas-backend
    APP_HOST: tsaas-api.$OPENSHIFT_DOMAIN
  environment:
    name: develop
    url: http://tsimulus-cluster.$OPENSHIFT_DOMAIN
  except:
    - master
    
publish:
  <<: *publish
  stage: publishToNexus
  tags:
    - shared
  except:
    - master
