---
## Used to provide the location of the openapi.json file.
## If jsonPath is empty the chart try to get a json file at the jsonUrl address. 
## The server fields have to use to add a custom server.
swaggerui :
  jsonPath : ""
  jsonUrl : https://raw.githubusercontent.com/cetic/tsimulus-saas/master/oas/api-doc/openapi.json
  server :
    description: "TSIMULUS endpoint"