kind: Service
apiVersion: v1
metadata:
  name: tsaas-backend
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: tsaas-backend 
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: tsaas-backend
  name: tsaas-backend
  annotations:
    openshift.io/image.insecureRepository: "true"
spec:
  serviceName: tsaas-backend
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      run: tsaas-backend
  template:
    metadata:
      labels:
        run: tsaas-backend
    spec:
      containers:
      - name: tsaas-backend
        image: nexus.ext.cetic.be:8083/cetic/tsaas-backend
        stdin: true
        tty: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        #- name: SEED_NODES
        #  value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
        - name: BINDING
          value: 0.0.0.0
        #livenessProbe:
        #  tcpSocket:
        #    port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        status:
          dockerImageRepository: nexus.ext.cetic.be:8083
