kind: Service
apiVersion: v1
metadata:
  name: akka-seed
spec:
  ports:
  - protocol: TCP
    port: 2551
    targetPort: 2551
  selector:
    run: akka-seed  
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: akka-seed
  name: akka-seed
  annotations:
    openshift.io/image.insecureRepository: "true"
spec:
  serviceName: akka-seed
  podManagementPolicy: "Parallel"
  replicas: 2
  selector:
    matchLabels:
      run: akka-seed
  template:
    metadata:
      labels:
        run: akka-seed
    spec:
      containers:
      - name: akka-seed
        image: nexus.ext.cetic.be:8083/cetic/tsimulus-cluster-akka-backend
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SEED_NODES
          value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
        - name: HOSTNAME
          value: $(POD_NAME).akka-seed
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
        status:
          dockerImageRepository: nexus.ext.cetic.be:8083