kind: Service
apiVersion: v1
metadata:
  name: tsimulus-cluster-play-frontend
spec:
  type: NodePort
  selector:
    app: tsimulus-cluster-play-frontend
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 9000
    targetPort: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tsimulus-cluster-play-frontend
  annotations:
    openshift.io/image.insecureRepository: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsimulus-cluster-play-frontend
  template:
    metadata:
      labels:
        app: tsimulus-cluster-play-frontend
    spec:
      containers:
      - image: nexus.ext.cetic.be:8083/cetic/tsimulus-cluster-play-frontend
        name: tsimulus-cluster-play-frontend
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 9000
        - name: management
          containerPort: 8558
        readinessProbe:
          tcpSocket:
            port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
      status:
        dockerImageRepository: nexus.ext.cetic.be:8083