openapi: 3.0.0
info:
  title: Tsimulus as a Service
  description: |
    Websocket configuration api serving tsimulus time series simulations.
    The websocket is located at the path  /socket
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: local
  - url: 'http://tsaas-api.openshift.ext.cetic.be'
    description: dev-online
paths:
  /stream:
    get:
      description: List all the available configurations
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebsocketConfiguration'
    post:
      description: Posts a stream configuration and assigns a stream id
      requestBody:
        content:
          application/json':
            schema:
              $ref: '#/components/schemas/StreamConfiguration'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebsocketConfiguration'
  '/stream/{id}':
    parameters:
      - $ref: '#/components/parameters/streamIdParam'
    get:
      description: 'Gives the configuration for the stream with id {id}'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebsocketConfiguration'
        '204':
          description: No Content
    post:
      description: 'Post a configuration for the stream with id {id}'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamConfiguration'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebsocketConfiguration'
    delete:
      description: 'Deleted configuration for the stream with id {id}'
      responses:
        '204':
          description: No Content
  '/stream/{id}/act':
    parameters:
      - $ref: '#/components/parameters/streamIdParam'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserFeedback'
              example:
                msg: Stream stopped
        '202':
          description: Accepted
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/UserFeedback'
                  - $ref: '#/components/schemas/Status'
              example:
                oneOf:
                  - msg: Streaming valid
                  - running: false
                    configured: true
        '449':
          description: Retry With
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserFeedback'
              example:
                msg: Stream not configured.
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserFeedback'
              example:
                msg: Streaming could not start because of <ERROR MESSAGE>
components:
  parameters:
    streamIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 71f0d26e-f3aa-4f04-868b-5aaf304dfe5b
  schemas:
    Action:
      type: object
      properties:
        action:
          type: string
          enum:
            - start
            - stop
            - status
            - validate
    UserFeedback:
      type: object
      description: User feedback
      properties:
        msg:
          type: string
    Status:
      type: object
      properties:
        running:
          type: boolean
        configured:
          type: boolean
    StreamConfiguration:
      type: object
      properties:
        speed:
          oneOf:
            - $ref: '#/components/schemas/Speed'
            - $ref: '#/components/schemas/SpeedFactor'
        template:
          $ref: '#/components/schemas/Template'
        config:
          $ref: '#/components/schemas/TsimulusConfiguration'
      example:
        example:
          config:
            generators:
              - name: daily-generator
                type: daily
                points:
                  '6:00:00.000': 11
                  '12:00:00.000': 12
                  '18:00:00.000': 11
                  '0:00:00.000': 12
              - name: noisy-daily
                type: aggregate
                aggregator: sum
                generators:
                  - daily-generator
                  - type: arma
                    model:
                      phi:
                        - 0.5
                      std: 0.25
                      c: 0
                      seed: 159357
                    timestep: 180000
                    origin: '2018-10-01 0:00:00.000'
            exported:
              - name: tlm_1
                generator: noisy-daily
                frequency: 3600000
            from: '2018-10-01 00:00:00.000'
            to: '2018-12-01 00:00:00.000'
          template:
            template: ''
            timeVariable: t
            nameVarialbe: name
            valueVariable: x
          type: tsimulus
          speed: 3600
    Speed:
      type: string
      enum:
        - inf
        - realtime
    SpeedFactor:
      type: number
    Template:
      type: object
      properties:
        template:
          type: string
          description: Apache FreeMarker template.
          externalDocs:
            url: 'http://www.freemarker.org'
            description: Apache FreeMarker template engine
        timeVariable:
          type: string
          description: name of the time variable
        nameVariable:
          type: string
          description: name of the series name variable
        valueVariable:
          type: string
          description: name of the value variable
    TsimulusConfiguration:
      description: Tsimulus time series simulator configuration json
      externalDocs:
        url: 'https://tsimulus.readthedocs.io/en/latest/'
        description: 'Tsimulus, a realistic time series simulator'
    WebsocketConfiguration:
      type: object
      properties:
        streamId:
          type: string
          format: uuid
          example: 71f0d26e-f3aa-4f04-868b-5aaf304dfe5b
        streamConfig:
          $ref: '#/components/schemas/StreamConfiguration'
externalDocs:
  url: 'https://git.cetic.be/TSimulus/tsimulus-saas'
  description: 'Tsimulus as a service git repo'
  
